import ReactDOM from "react-dom";
import React from "react";
import { MainApp } from "./components/09-useContext/MainApp";
// import { TodoApp } from "./components/08-useReducer/TodoApp";
// import { CallbackHook } from "./components/06-memos/CallbackHook";
// import { Padre } from "./components/07-tarea-memo/Padre";
//import { LayoutEffect } from "./components/05-useLayaoutEffect/LayoutEffect";
//import { Memoriza } from "./components/06-memos/Memoriza";
//import { FocusScreen } from "./components/04-useRef/FocusScreen";
//import { RealExapleUseRef } from "./components/04-useRef/RealExapleUseRef";
//import { HookApp } from "./HookApp";
//import { CounterApp } from "./components/01-useState/CounterApp";
//import { CounterWihtCustomHooks } from "./components/01-useState/CounterWihtCustomHooks";
//import { SimpleForm } from "./components/02-useEffect/SimpleForm";
//import { FormWithCustomHook } from "./components/02-useEffect/FormWithCustomHook";
//import { MultipleCustomHooks } from "./components/03-examples/MultipleCustomHooks";
//import { MemoHook } from "./components/06-memos/MemoHook";
// import "./components/08-useReducer/intro-reducer";

ReactDOM.render(<MainApp />, document.getElementById("root"));
